### ISSUE TITLE
Consultation Chat module long texts get cut and not visible

### ISSUE THREAD

**Issue by mhdosman** [UNICEFECAR/USupport-entry-bundle#104]
**Describe the bug**
Consultation Chat module long texts get cut and not visible

**To Reproduce**
1. Start a consultation, 
2. Start texting, type a long message 
3. The remaining part gets invisible,

**Expected behavior**
To go to second line

**Screenshots**
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/27133b9a-2df1-44a6-93b5-f003dface9fe)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser CHROME
 -

**Comment by mhdosman** [comment]
another screenshot
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/4a751f81-89de-44a8-9147-92ed115e74ef)

**Comment by sebastian-7DIGIT** [comment]
Ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
Changes ready for review.
