### ISSUE TITLE
On a laptop display with a resolution of 1366 x 768 pixels, the video and chat modules are arranged vertically, each occupying half of the screen

### ISSUE THREAD

**Issue by mhdosman** [UNICEFECAR/USupport-entry-bundle#106]
**Describe the bug**
On a laptop display with a resolution of 1366 x 768 pixels, the video and chat modules are arranged vertically, each occupying half of the screen

**To Reproduce**
1. Start a consultation
2. as in the screenshot

**Expected behavior**
To arrange video/chat module in a better way, showing chat module (30% on the right for example)

**Screenshots**
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/42aca7d7-a5ab-437c-b092-2af8301b9a63)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome, Edge,

**Comment by sebastian-7DIGIT** [comment]
Ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych could you please let us know if further adjustments are required for this topic?

**Comment by Gaskevych** [comment]
Dear @MiriamObibi lets test this one when you have time?

**Comment by Gaskevych** [comment]
Dear @mhdosman  can you please help with testing this one?

**Comment by mhdosman** [comment]
Dear @Gaskevych  you can close it, ,it is fixed now

**Comment by mhdosman** [comment]
Dear @Gaskevych  it is fixed now thanks
