### ISSUE TITLE
Show more specialists 

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#109]
**Describe the bug**
"Show more" functionality error
Website interface in "How it Works" -> Meet our providers

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Website interface -> How it Works
2. Click on "Show More"

**Expected behaviour**
All providers should be presented regrdless of their set availability

**Screenshots**
<img width="1784" alt="MicrosoftTeams-image (2)" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/4fd5aa98-af8e-424e-816d-70235b7d2448">

**Additional context**
Functionality should be checked and adjusted

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych changes were implemented and deployed. Ready to review the new changes.

**Comment by Gaskevych** [comment]
It works, but there is a minor translation mistake, will create a new issue now.
