### ISSUE TITLE
Dynamic show of filter options for providers

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#110]
To create a dynamic show of the filter options for the providers' search.

**Comment by sebastian-7DIGIT** [comment]
Requirements:

- Remove Provider types
- Remove prefer not to say -> Provider registration form as well
- Only the free consultations toggle should be set to enabled -> the user should not be able to disable it (as per requirement for KZ not to charge for consultations)
- Add a dynamic list for spoken languages based on current existing providers 
- Remove the maximum price

**Comment by georgiganchev-7DIGIT** [comment]
Database update required once deployment complete @sebastian-7DIGIT

**Comment by sebastian-7DIGIT** [comment]
Ready for deployment, DB updates not required.

**Comment by sebastian-7DIGIT** [comment]
Changes are ready for review
