### ISSUE TITLE
Editing the translation

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#112]
Edit the translation of the homepage and other website texts as indicated in the attached files. 
[Copy of USupport-Translations_Kazakhstan.xlsx](https://github.com/UNICEFECAR/USupport-entry-bundle/files/14585053/Copy.of.USupport-Translations_Kazakhstan.xlsx)
[USupport-Translations-v1.11_Aigul &Sasha.xlsx](https://github.com/UNICEFECAR/USupport-entry-bundle/files/14585054/USupport-Translations-v1.11_Aigul.Sasha.xlsx)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych I am adding a new file for translations containing new elements that need to be translated into Kazakh and Russian. These correspond to the changes made for issue #111.

Please take note of the entries marked in orange in the file, as we will need your input on those.

[USupport-Translations-v1.12_7Digit.xlsx](https://github.com/UNICEFECAR/USupport-entry-bundle/files/15014487/USupport-Translations-v1.12_7Digit.xlsx)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych I think there were no further comments for this issue following our update. If so could we please close this issue?

**Comment by Gaskevych** [comment]
All the additional edits will be tracked under the issues #116
