### ISSUE TITLE
Changing the order of the FAQ

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#113]
when adding the FAQ as a translation of the English version, the display order is different for Russian and Kazakh (the order for English and Russian questions is correct). Would be good to change the order for Kazakh FAQ not to start from the question related to the provider.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych note added please see here [link](https://github.com/UNICEFECAR/USupport-entry-bundle/blob/gitbook/docs/ui-usage-manuals/country-admin.md#9-manage-faqs)
