### ISSUE TITLE
Translating uSupport to Polish and Ukrainian

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#116]
Please translate the platform to Ukrainian and Polish (the Excel file has been shared via email). Thanks!

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych please find attached the exported translations from the platform including Polish and Ukrainian.

[Usupport-translations-v2.xlsx](https://github.com/user-attachments/files/15765000/Usupport-translations-v2.xlsx)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych changes deployed to both environments staging and production, ready for review.
