### ISSUE TITLE
Remove the second Kazakhstan from the dropdown of countries

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#120]
Remove the second Kazakhstan from the country selection on the website (production environment) 

<img width="941" alt="screen- lz" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146723847/5e205e22-53ee-4757-934d-caf6e6218958">

**Comment by sebastian-7DIGIT** [comment]
Duplicated country was removed.
