### ISSUE TITLE
Upload the new illustrations to uSupport 

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#122]
Please add the additional illustration for About us, How it works and information portal from Figma: 

[https://www.figma.com/file/Lay1M0ytvm9PpTwAPdqRsQ/USupport_Aia?type=design&node-id=0-1&mode=design&t=1FrHKRRsQ1WoH0k2-0  ](url)

**Comment by sebastian-7DIGIT** [comment]
https://www.figma.com/design/Lay1M0ytvm9PpTwAPdqRsQ/USupport_Aia?node-id=0-1&t=VCpASu57s8huCj1c-0

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych changes deployed to both environments staging and production
