### ISSUE TITLE
uSupport logo not loading 

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#124]
uSupport logo is not always loading when refreshing the page. 

![Annotation 2024-05-22 131444](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146723847/4ddb2d03-1f14-4c5b-ac6b-f7540c982c94)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych issue should be fixed, ready for review.
