### ISSUE TITLE
Mistranslation of text

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#126]
From now on any mistranslations with their placement and screenshots will be fixated in following table:
https://docs.google.com/spreadsheets/d/1zMjNlUAuD47osRgS8jUS4npFhgPI2L2z1lwHeqyEg2I/edit?usp=sharing 

**Desktop **
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Smartphone **
 - Device: Xiaomi redmi 10s
 - OS: Android 13
 - Browser chrome
 - Version latest

**Comment by sebastian-7DIGIT** [comment]
@fomap  It is a good approach to check the translations that are added directly on the website. However, for us, the approach you suggest will make it hard to understand the adjustments that need to be made (especially for languages that we do not understand) as well as keep track of the state of the translations.

I have discussed with @Gaskevych the creation of a shared space (e.g., Google Drive) and a set of rules that we can follow to efficiently adjust the translations over time. We will share this once it is in place.

In the meantime, if you continue to find additional adjustments that are required and take notes in the file you shared, please note that they will need to be transferred to the new file.
