### ISSUE TITLE
Changing the specialization of providers

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#128]
Please change the specialization of providers in line with the list shared by Aigul:

[Specialization for providers.docx](https://github.com/user-attachments/files/15550831/Specialization.for.providers.docx)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych , the Ukrainian and Polish translations are missing from the file. Please add the missing languages in the empty columns in the file below. Thank you.

[Specialization.for.providers.docx](https://github.com/user-attachments/files/15586395/Specialization.for.providers.docx)

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment, database adjustments needed beforehand.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych  changes deployed to both environments staging and production, ready for review.
