### ISSUE TITLE
Wrong address in generated email

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#131]
**Describe the bug**
After joining as provider generated email is readdressing to https://staging.usupport.online/provider/login instead of https://usupport.online/provider/login

**To Reproduce**
1. Register as provider
2. Receive generated email
3. See error

**Expected behavior**
Seeing https://usupport.online/provider/login in the email

**Screenshots**
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/cdadf1d3-f29f-43c7-86dc-f35529398335)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version latest

**Comment by sebastian-7DIGIT** [comment]
Changes were deployed, and issue should be fixed.
