### ISSUE TITLE
Slow loading time of the articles in the information portal

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#140]
On the information portal (tested on the desktop), articles are loading slow, when scrolling down to see more articles it is taking a lot of time.

**Comment by Gaskevych** [comment]
Dear @sebastian-7DIGIT  and @vasilen-7DIGIT  lets try to also prioritize investigation of this issue as loading time remains extremely slow on production.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych , please advise if there is any action point required for this issue. If not,can we please close it?
