### ISSUE TITLE
Change the abbreviation of the language for the Ukrainian language on Poland staging

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#141]
In the language bar for Poland, when you select Ukrainian language it is displayed as UK, should be either UKR or UA (sorry, not sure where it is in the translation table) .

![WhatsApp Image 2024-10-16 at 11 48 04](https://github.com/user-attachments/assets/133479ca-9bd9-4c85-9d40-81b8e5088c29)

**Comment by sebastian-7DIGIT** [comment]
Issue fixed.

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT for the production is should be changed as well. it is currently shows UK

**Comment by Gaskevych** [comment]
Also, for the Poland Q&A page the abbreviation is still UK:

<img width="949" height="466" alt="Image" src="https://github.com/user-attachments/assets/dcd41438-a48f-4418-ae8e-63ecc8979dd4" />
