### ISSUE TITLE
Add one more field for the year of birth + remove the "i am over 13' checkbox

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#146]
1) For the client registration, please add one more option to the current dropdown to say 'parent/caregiver'.
2) Remove the checkbox on the registration screen saying "I am over 13 years old'. 

![WhatsApp Image 2024-10-22 at 15 31 43](https://github.com/user-attachments/assets/badbe319-f663-4eb0-9a64-6d2ee9908abf)
![WhatsApp Image 2024-10-22 at 15 31 42](https://github.com/user-attachments/assets/bc75bd9b-a8dc-4316-9048-1209c1f933b7)

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT please note i changed the priority to high s it is needed for Kazakhstan. Please prioritise if possible.

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT so the final agreement is: add a line 'Parent/Caregiver" to the current dropdown options.  Dropdown options should provide years of birth for users from 10 to 29 years old (inclusive). 
The checkbox "I am over 13 years old" should be changed to "I am over 10 years old"

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych could you please confirm if this will be only for Kazakhstan or for all countries?
