### ISSUE TITLE
Text display on the mobile app (no wrapping) 

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#150]
On the mobile app (IOS) for the information portal the categories of articles are not wrapping - the word is display partially on the right side (screenshot below)

![WhatsApp Image 2024-11-18 at 15 28 17](https://github.com/user-attachments/assets/79780be2-2b09-4a7e-9880-0b6efbe50d89)

**Comment by sebastian-7DIGIT** [comment]
The categories are scrollable left and right. 

https://github.com/user-attachments/assets/07360bd2-a235-4183-8667-e049435b7a26

**Comment by Gaskevych** [comment]
The field is scrollable left and right.
