### ISSUE TITLE
Wrong translation in the client app

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#155]
In the client app (IOS) when the client is registering with the Russian language, the two fields : Continue and Year of Birth in Ukrainian. I have changed the "Continue' button in the translation table and highlighted in blue. However, for the Year of birth the translation in the Russian column is correct. PLease investigate and correct. 

![WhatsApp Image 2024-11-20 at 10 13 47 (1)](https://github.com/user-attachments/assets/7c98cc8e-8c0a-499e-bdb2-03b9dc883e04)
![WhatsApp Image 2024-11-20 at 10 13 47](https://github.com/user-attachments/assets/035b21c9-f258-46b4-902d-65a91d6263e0)

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented and deployed. Ready for test @Gaskevych

**Comment by Gaskevych** [comment]
Two fields are sill in Ukrainian (should be in Russian) - please see below. @sebastian-7DIGIT 

![WhatsApp Image 2024-12-09 at 13 50 13](https://github.com/user-attachments/assets/0a58816c-7316-4e80-a438-9ab16fe62ec0)
