### ISSUE TITLE
Wrong language while registration using app

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#163]
Describe the bug
When registering (whether by email or anonymous) using mobile app on Russian language there is other language on display

To Reproduce
Open application
Register as user using Russian language

Screenshots

![Image](https://github.com/user-attachments/assets/e887ea0a-810c-4015-a5e9-e454a380ce40)
![Image](https://github.com/user-attachments/assets/f8bbab43-a545-4a55-b316-1f23788ea873)

Smartphone (please complete the following information):
Device: Xiaomi Redmi 10S
OS: Android 13.
Android app

**Comment by Gaskevych** [comment]
Same as issue 155.

**Comment by sebastian-7DIGIT** [comment]
@fomap @Gaskevych, changes were deployed, ready to be tested.
