### ISSUE TITLE
Wrong language in pop up window

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#164]
**Describe the bug**
On Kazakhs version of the site, after confirming consultation hour pop up windows with wrong language on the button appears. It also shows when you change time slot

**To Reproduce**
1. Go to consultation scheduling
2. Chose time and professional 
3. See error

**Expected behavior**
The same button content as in the application

**Screenshots**
On website (incorrect)
![Image](https://github.com/user-attachments/assets/526a2a45-173f-45e9-a952-22f704f69dd0)
![Image](https://github.com/user-attachments/assets/8f073234-12e2-49fd-97be-3ce81b8bd90c)

In application (correct)
![Image](https://github.com/user-attachments/assets/43b8083c-dbda-4270-8940-6d32169d5336)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: latest

**Comment by sebastian-7DIGIT** [comment]
@fomap @Gaskevych, changes were deployed, ready to be tested.

**Comment by Gaskevych** [comment]
@fomap please confirm. Thanks!
