### ISSUE TITLE
Text edits for USupport

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#18]
Issue Description
The text needs to be updated in line with the table. 

Expected Behavior
PLease update the text (highlighted in the attached table)  for the Website UI and Client UI tabs. 

Proposed Solution (optional)
https://docs.google.com/spreadsheets/d/115O04YVOGtGpns4wAKtUvhjgDIJgEafm/edit?usp=sharing&ouid=113718499663484912454&rtpof=true&sd=true

**Comment by Gaskevych** [comment]
@vasilen-7DIGIT I updated the link, can you please check? Thanks!

**Comment by vasilen-7DIGIT** [comment]
✅
