### ISSUE TITLE
To add password protection for the USupport URL and remove it from google search

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#20]
**Describe the bug**
We need to ensure that the current URL is password protected and everyone with the ink cant use the website. 

**Expected behavior**
Add password protecton for  the URL with some hardcoded password. Also, remove the site from google search.
https://developers.google.com/search/docs/crawling-indexing/remove-information

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vasilen-7DIGIT** [comment]
The website has been protected with a password, required within a modal.

**Comment by vasilen-7DIGIT** [comment]
The password modal should have an X button that when pressed, should close the tab window.
