### ISSUE TITLE
Add "registration by phone number" feature

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#21]
**Add registration by phone number**
Currently, there is only 1 way to register - using an email address, however during beta-testing significant part of the group reported that it would be nice to have other registration options

**Solution**
To be exact, they talked about adding registration by phone number feature to platform. 

**Context**
While I am aware that a lot of people do have existing email address that they use, phone became more popular tool in todays world (For a context, in Kazakhstan you are required to have a phone number if you have a phone so its would be easier to register for a younger teenagers who yet may not have an email address)

**Comment by Gaskevych** [comment]
Will close it for now since it was agreed to study more why this feature is requested.
