### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#22]
**Dark theme for app and cite**
Currently there is only one theme/color palette for platform and it is mainly white. During testing people complained that because everything is very bright their eyes get irritated. 

**Solution**
Design and add dark theme

**Context**
While it is not impacting overall functionality it is a nice feature to have also considering that target audience likes to scroll phone before bed, where background is likely pitch black.
For example twitter has light/dim/dark themes that a lot of younger people will find more appealing
![TwtWhite](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/33217cec-f8b3-434e-92f1-d54e986dafec)

![TwtBlack](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/39d3c911-74df-4010-9ea3-e0a9c090ee7a)
![TwtDark](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/23f4f6b3-62a5-404c-b123-e3ddf01bd508)

**Comment by Gaskevych** [comment]
We will add the details from where to start - the app or the website - after the team meeting.

**Comment by Gaskevych** [comment]
Approved for implementation from UNICEF side for both mobile app and desktop version @sebastian-7DIGIT @vasilen-7DIGIT

**Comment by Gaskevych** [comment]
This is the same as issue#74. @sebastian-7DIGIT should we delete this one?

**Comment by sebastian-7DIGIT** [comment]
Yes, closing this issue as it was addressed under issue #74.
