### ISSUE TITLE
Gibberish in exported chat history

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#23]
**Description**
When user tries to export chat history, it creates a file that is full of gibberish. It is unexpected considering that chat history itself is readable on the platform

**To Reproduce**
Consultations -> Past -> See details

**Expected behavior**
Clear, readable and understandable text

**Desktop **
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 117.0.5938.150
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/0c9069a7-539a-409a-a2a0-f2f57e97690d)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/1633d12a-b1ae-4788-814f-b7a9e0144686)

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT Ready for deployment

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented and deployed to the staging environment. 

Ready for review.

**Comment by Gaskevych** [comment]
@fomap Can you please check again and confirm that all changes were implemented? Thanks!

**Comment by fomap** [comment]
Hello, yes, export works as expected 
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/905f9a7e-677b-4901-936d-faca8f289916)

**Comment by sebastian-7DIGIT** [comment]
The misaligned title issue as presented in #24 under the following comment [comment_link](https://github.com/UNICEFECAR/USupport-entry-bundle/issues/24#issuecomment-1780783528), was addressed.

@vasilen-7DIGIT Ready for redeployment.

**Comment by MiriamObibi** [comment]
Reviewed. There are some follow up propositions on this. 

1. For the export,  kindly remove the bubbles or make them smaller and concise. They appear too large and will require that too many pages are exported for a lengthy chat consultation. 
2. The system messages are aligned, but the margins of the actual messages(chats) are too small on the sides (screenshot attached)
![MicrosoftTeams-image (7)](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146742938/1571f992-6a56-4fd3-815b-c1ffe81a072d)
3. Include time stamp to the export.

**Comment by sebastian-7DIGIT** [comment]
> Reviewed. There are some follow up propositions on this.
> 
> 1. For the export,  kindly remove the bubbles or make them smaller and concise. They appear too large and will require that too many pages are exported for a lengthy chat consultation.
> 2. The system messages are aligned, but the margins of the actual messages(chats) are too small on the sides (screenshot attached)
>    ![MicrosoftTeams-image (7)](https://private-user-images.githubusercontent.com/146742938/290168715-1571f992-6a56-4fd3-815b-c1ffe81a072d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTY3NjgsIm5iZiI6MTcwMzE1NjQ2OCwicGF0aCI6Ii8xNDY3NDI5MzgvMjkwMTY4NzE1LTE1NzFmOTkyLTZhNTYtNGZkMy04MTViLWMxZmZlODFhMDcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMTAxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDc1MzYxMGUxMTRjNzYyYjAzMWZhNzM2Yjc2M2NiODc0MTc5ODY2Nzc4N2U2YjA0ODFkMzhhYjY1NDRhNmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Av_ZqzTC4yt0692MCjt-Pw32lM0H5HIqDLzhtKSOKk)
> 3. Include time stamp to the export.

This additional adjustments are transferred to a new Issue #87
