### ISSUE TITLE
Misaligned timestamp in system messages

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#24]
**Description**
In consultations' chat history a timestamp of certain action is misaligned inside the message.   

**To Reproduce**
1) Consultations
2) Click past
3) Go to "See details"

**Expected behavior**
Timestamp and text being on the same elevation level

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 117.0.5938.150

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/aa9a6f9c-0108-47f4-aa32-2b09236aad65)

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented and deployed to the staging environment. 

Ready for review.

**Comment by fomap** [comment]
Timestamp looks good, not sure if name of psychologist is supposed to be that way or if it needs separate ticket 
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/f41d4805-4ef8-4864-8006-5a0a1ac37f86)

**Comment by sebastian-7DIGIT** [comment]
@fomap noted, we will address the miss-aligned name issue under Issue #23

**Comment by MiriamObibi** [comment]
Reviewed with case #87 
Verified ok.
