### ISSUE TITLE
Provider registration/login 

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#25]
**Describe the bug**
When updating the page, you need to re-enter your login and password.

**To Reproduce**
1. Open a new browser windows
2. Go to [https://staging.usupport.online/provider/](https://staging.usupport.online/provider/)
3. Enter credentials and login
4. Refresh the the page fast shortly after loggin in 
5. You will be logged out and sent to the country and language selector

**Expected behavior**
Remain logged in every time even if you refresh the page fast

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Mozilla, Opera, Safari, Yandex]
The replication was successfull on the following browsers: Chrome, Mozilla, Opera, Safari, Yandex

**Smartphone:**
 - Device: [iphone, samsung]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 Could not replicate the bug on ios
Successful  replecated the bug on android device
The replication was successfull on the following browsers: Chrome

**Additional context**
The bug appears 2 - 3 times out of 5 on a new browser window

**Comment by sebastian-7DIGIT** [comment]
This issue will be addressed under issue #58. Closing this issue.
