### ISSUE TITLE
Provider calendar 

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#26]
**Is your feature request related to a problem?**
Doesnt show if there are other providers online at the same time.

**Describe the solution you'd like**
Want to see if other providers are online. 
For specialists, this may be a “hint” at what time there are the fewest specialists to offer their service.

**Additional context**
Currently there is no way to see if there are providers online.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych, please advise if there is any action point required for this issue. If not lets please close it.
