### ISSUE TITLE
Notification by other means than email

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#27]
**Is your feature request related to a problem?**
It is inconvenient when notification of a consultation arrives only by email.

**Describe the solution you'd like**
To add notification by WhatsApp or other messenger applications or services.

**Additional context**
Currently there are very few ways to recieve notifications by.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych, please advise if there is any action point required for this issue. If not lets please close it.
