### ISSUE TITLE
Activity history in provider

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#28]
**Is your feature request related to a problem?**
It is not clear why this section is needed, because it’s repeated in analytics and in the calendar.

**Describe the solution you'd like**
Perhaps it is possible to make some short notes invisible to the client about the progress of the consultation or the result, whether the request was resolved or not.

**Additional context**
Possibly remove/refactor the Activity history page in provider

**Comment by sebastian-7DIGIT** [comment]
Additional information and a more in-depth discussion are necessary for this issue.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych, please advise if there is any action point required for this issue. If not lets please close it.
