### ISSUE TITLE
Provider clients missing special Kazakh letters

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#30]
**Describe the bug**
In the Kazakh version of the platform, Kazakh letters (ә, і, ң, ғ, ү, ұ, қ) are not shown.

**Expected behavior**
The correct special charactesr to be shown

**Screenshots**
![Screenshot 2023-10-10 at 15 53 08](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/bdd36d8c-14ea-44b5-9a47-93ca24e6609c)

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Yandex, Opera]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [iphone]
 - OS: [latest ios]
 - Browser [Safari, Chrome]
 - Version [latest]

**Additional context**
We could not reproduce the bug, additional information is needed. As shown in the attached image some of the letters which were mentioned are present inside the platform.

**Comment by Gaskevych** [comment]
@fomap is there a chance you know what was the phone model of the person for whom the Kazakh letters were not displayed?
