### ISSUE TITLE
Not  possible to login into client through Yandex browser

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#32]
**Describe the bug**
Not  possible to login into client through Yandex browser.

**Expected behavior**
To be able to successfully to login through the Yandex browser. 

**To Reproduce**
1. Go to [https://staging.usupport.online/client](https://staging.usupport.online/client/login) in Yandex browser
2. Login with your credentials

**Screenshots**
![Screenshot 2023-10-10 at 16 25 25](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/02fdbbb0-8fa4-4fc2-b2c8-958ea09b4daf)

**Desktop:**
 - OS: [Mac]
 - Browser [Yandex]
 - Version [latest]

**Smartphone:**
 -Device: [iphone]
 -OS: [latest ios]
 -Browser [Yandex]
 -Version [latest]

**Additional context**
Additional information needed, because there was no issue with the login on the Yandex browser after many attempts.

**Comment by Gaskevych** [comment]
Anel will test one more time, if everything works, we will close this comment.

**Comment by fomap** [comment]
Login through Yandex browser (both mobile and desktop) works as expected without any bugs.
