### ISSUE TITLE
Provider profile remove address

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#33]
**Is your feature request related to a problem?**
Why the  provider’s address is indicated in the profile?

**Describe the solution you'd like**
Remove the address from the profile.

**Comment by Gaskevych** [comment]
We need to make it invisible for the clients. Can stay there for the country admin

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych Currently, the information is displayed in the way you have described it. Please see bellow what information is displayed on each platform.

### Client View

<img width="1501" alt="Screenshot 2023-10-12 at 10 53 49" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/ae732b57-b242-457b-ad95-347977bef091">


### Provider View
<img width="1503" alt="Screenshot 2023-10-12 at 10 52 57" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/80d8c0bd-8c92-4630-8109-edbb73fa8a97">

### Country Admin View

<img width="1503" alt="Screenshot 2023-10-12 at 10 54 37" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/ef772459-8260-44dc-b49c-f68e847d00a6">

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT  can we remove it from the client view? So clients do not see the address box at all? Thanks!

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych as presented in the first picture above, there is no address-related information presented on the Clients view.

As previously discussed this issue was addressed some time ago.

Closing the issue as no further actions are required.
