### ISSUE TITLE
While scheduling consultation the clients can't filter providers based on free time slots

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#35]
**Is your feature request related to a problem?**
Clients can't filter providers based on free time slots.

**Describe the solution you'd like**
Filter options for the clients to be able to search the providers by free time slots.

**Additional context**
Clients had to manually go through profiles and find free consultants. For example I want to filter by free from 10 to 12 and the list of all available.

**Comment by MiriamObibi** [comment]
@Gaskevych did we agree to do this or not?

**Comment by Gaskevych** [comment]
No. We decided to pilot it first and then see if this request will come up from the clients or not.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych seems this issue can be closed for now. Please could you update it ?
