### ISSUE TITLE
Remove the emergency help button in the registration screens

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#37]
**Is your feature request related to a problem? Please describe.**
Remove the emergency help button in the registration screen.

**Describe the solution you'd like**
Remove the emergency help button in registration screen.

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT Ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented and deployed to the staging environment. 

Ready for review.
