### ISSUE TITLE
The navigation is transparent

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#38]
**Describe the bug**
The navigation is transparent, in provider and client

**To Reproduce**
1. Go to [https://staging.usupport.online/provider](https://staging.usupport.online/provider) or [https://staging.usupport.online/client](https://staging.usupport.online/client)
2. Scroll down on a page with longer content

**Expected behavior**
The navigation to be solid colour

**Screenshots**
![Screenshot 2023-10-10 at 17 28 02](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/3549d57b-70b2-49b2-9cb7-aa80c1527425)

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone:**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Chrome , Safari]
 - Version [latest]

**Comment by sebastian-7DIGIT** [comment]
### Checklist

- [x] Implement changes
- [x] Code Review
- [ ] Test 
- [ ] Deploy
