### ISSUE TITLE
Add more notification options in provider settings

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#40]
**Is your feature request related to a problem?**
Notifications of upcoming consultations are sent to the registered email. In the settings, you can choose one of the four proposed notification options with 15 minutes step. Providers are unanimous that there is a need to select several notification options at the same time, for example, 60 minutes and 15 minutes.

**Describe the solution you'd like**
Ability to select multiple notification options in provider settings. Example 60 and 15 minutes.

**Comment by gravitz** [comment]
@Gaskevych Priority 3 should be fine

**Comment by MiriamObibi** [comment]
We had agreed to make it priority 3 put if it can be done with the priority 1 or 2  issues, I think that's fine. Its a relevant ask

**Comment by sebastian-7DIGIT** [comment]
Changes were deployed and tested. The issue is ready for review.

**Comment by Gaskevych** [comment]
@MiriamObibi can you please test it?

**Comment by MiriamObibi** [comment]
Works as expected. Verified!
