### ISSUE TITLE
Additional hour options when scheduling consultations

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#41]
**Is your feature request related to a problem? Please describe.**
The providers noted that choosing a time step for scheduling consultations of 1 hour is not always convenient, and expressed a wish to set the period to 30 minutes.

**Describe the solution you'd like**
Add additional hour options when scheduling consultations.

**Comment by Gaskevych** [comment]
Agreed not to change the session duration for now.
