### ISSUE TITLE
Changing tabs during call interrups the call

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#43]
**Is your feature request related to a problem? Please describe.**
When changing tabs, for example if I want to look at the calendar during a call, the call is interrupted, which is probably not very convenient either.

**Describe the solution you'd like**
Keep the call active when changing tabs.

**Describe alternatives you've considered**
Maybye a floating window with the video call should appear when switching between tabs.

**Additional context**
Example call (provider on the left, client on the right):
<img width="1650" alt="Screenshot 2023-10-11 at 14 11 39" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/01f668b4-aff3-4554-a620-61d0e0ebb29b">

Provider (left) switches the tab and the call is interupted for the client(right):
<img width="1664" alt="Screenshot 2023-10-11 at 14 10 40" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/6be5e4b5-a8ef-40e2-ba12-e1e70c88972e">

Provider rejoining the call (left):
<img width="1676" alt="Screenshot 2023-10-11 at 14 10 57" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/19e2684b-429f-4ea2-888b-c3756dbb6df7">

<img width="1540" alt="Screenshot 2023-10-11 at 14 11 30" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/e51f838b-f6ef-4d17-8691-9c60c01356ae">

**Comment by sebastian-7DIGIT** [comment]
The term "tabs" in this context actually refers to various pages within the platform, with each page serving as a distinct section of the platform. The video consultation feature is specifically available on one of these platform pages. Technically, it's not feasible to keep the consultation functionality running across different pages.

However, if a provider or client wishes to navigate to another page while keeping the consultation active, they can achieve this by opening a new browser tab (essentially, a fresh browser window) and visiting the desired page. In essence, this isn't a platform issue; it's more about understanding the distinction between browser pages and tabs.

**Comment by gravitz** [comment]
> The term "tabs" in this context actually refers to various pages within the platform, with each page serving as a distinct section of the platform. The video consultation feature is specifically available on one of these platform pages. Technically, it's not feasible to keep the consultation functionality running across different pages.
> 
> However, if a provider or client wishes to navigate to another page while keeping the consultation active, they can achieve this by opening a new browser tab (essentially, a fresh browser window) and visiting the desired page. In essence, this isn't a platform issue; it's more about understanding the distinction between browser pages and tabs.

@sebastian-7DIGIT navigating to another page using a new browser tab wouldn't solve the problem (when tested back in July, switching browser tabs/windows interrupted the video session)

**Comment by Gaskevych** [comment]
We retested the issue - when the client during the session wants to book the second time slot and clicks on 'calendar' the session is interrupted. The same with provider - when provider wants to check the calendar, the session is interrupted. @sebastian-7DIGIT

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych  if the client wants to book another session while attending a video consultation, they should use a different tab or browser window.  As described here [link](https://github.com/UNICEFECAR/USupport-entry-bundle/issues/43#issuecomment-1768558510). The same applies for the providers if they want to check something else on the web platform while attending an online consultation. 

This is how the platform should be operating at this point following the requirements after which it was built. According to this, I can say that your remark is not an issue but instead a further improvement which we can investigate and come up with a solution if required.

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT please proceed with implementing BP's recommendations - clicking on the tab during the call should open the tab in a separate browser. Thanks!

**Comment by sebastian-7DIGIT** [comment]
New implementation ready in staging and production environment.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych this issue can be closed.
