### ISSUE TITLE
When texting, it is not always clear where to enter the message

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#45]
**Is your feature request related to a problem? Please describe.**
When texting, it is not always clear where to enter the message.

**Describe the solution you'd like**
More defined text input box that catches the eye and could be determined at a glance that is a text input.

Current text input for the messages:
<img width="284" alt="Screenshot 2023-10-11 at 15 09 14" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/d6b5d960-944b-42e3-9f0d-b861c4572800">

**Comment by sebastian-7DIGIT** [comment]
Changes are required in the mobile repo.
