### ISSUE TITLE
Sometimes I see myself as a “guest” while logged in as a provider

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#48]
**Describe the bug**
Sometimes I see myself as a “guest”. Clients do not see me as a specialist (provider). Kicks you out of your account, you have to refresh the page and log in again. 

**Expected behavior**
To not have any issues with the login(to not have to be kicked out and to login again) and to not have any issues like the clients seeing me as a "guest"

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 - Version [latest]

**Additional context**
Additional information is needed because we couldn't reproduce the bug after may attempts.

**Comment by Gaskevych** [comment]
Will close it since we discussed that the solution is to add the label for the providers' interface so they are not confused (covered by the issue #62

**Comment by Gaskevych** [comment]
Will close it since we discussed that the solution is to add the label for the providers' interface so they are not confused (covered by the issue https://github.com/UNICEFECAR/USupport-entry-bundle/issues/62
