### ISSUE TITLE
Keyboard covers the chat with a client on mobile devices

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#50]
**Describe the bug**
It’s impossible to write anything to a client on the phone, because the keyboard covers the chat window and you can’t see what’s being typed.

**To Reproduce**
1. Go to [https://staging.usupport.online/provider](https://staging.usupport.online/provider)
2. Login with your credentials
3. Join a consultation with a client
4. Click on the "chat" icon

**Expected behavior**
Enough clearance to be able to read and write messages to the client without issues. 

**Screenshots**
Screenshot of the issue:
![IMG_0571](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/739ceb6f-7da9-4d93-8090-8457d4a49e60)

**Smartphone (please complete the following information):**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 - Version [latest]

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT can we move the chat window a bit up? So the providers can see what they are typing?

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented and deployed. Ready in staging and production.
