### ISSUE TITLE
Mood tracker (mobile)

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#52]
**Is your feature request related to a problem? Please describe.**
The gradients are very large - to add more options. And to make it more frequent (The mood tracker can be used endlessly on the website, but only once in the mobile app)

**Describe the solution you'd like**
Making a mood questionnaire twice a day, in the morning and evening, or creating it in the form of a calendar, where you select by time not only emojis, but also color

Suggested result attached

![71f8a31e-5650-47f9-9e55-fa14294ae898](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/893e781e-b783-409b-80ed-3e3ba66a31f6)

**Comment by sebastian-7DIGIT** [comment]
Additional discussions and details are required for this issue.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych , please advise if there is any action point required for this issue. If not,can we please close it?
