### ISSUE TITLE
Accessibly issue

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#53]
**Describe the bug**
One of the consultants during the selection of a free slot sponsored by the company came up with the UNICEF/Example of a seminar campaign in Kazan - add accessibility (in Russian - «ЮНИСЕФ/Пример кампании семинара в Казани). Note: Kazan – capital city of the Republic of Tatarstan.

**To Reproduce**
1. Go to [https://staging.usupport.online/provider](https://staging.usupport.online/provider)
2. Login with your credentials
3. Go to "Campaigns"
4. Click on the three dots on the given campaign
5. Select "Add availability"

**Expected behavior**
Add accessibility (in Russian - «ЮНИСЕФ/Пример кампании семинара в Казани). Note: Kazan – capital city of the Republic of Tatarstan.

**Screenshots**
![7b90ca5c-065f-4ba9-8698-566cb7a4f6ab](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/3e90e3c5-fb07-49ae-b805-f105e73fcd3b)

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone:**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 - Version [latest]

**Additional Context:**
We will require more information for this issue. It seems that the required adjustment is related to the ability to translate campaign names.

**Comment by Gaskevych** [comment]
@gravitz @MiriamObibi just to highlight this for your information

**Comment by sebastian-7DIGIT** [comment]
Currently, when creating a campaign and specifying its name in English, there is no functionality implemented to handle translations in different interfaces. The name will be displayed exactly as entered by the creator.

We're not certain if this feature is necessary, as far as we know, campaigns will be generated for specific countries. This implies that the name of the campaign can be added directly in the primary language used in that specific country. If this is a requirement on your end, we will need to consider it as an additional feature for the campaigns. Please inform us of your preferences.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych, please advise if there is any action point required for this issue. If not lets please close it.

**Comment by Gaskevych** [comment]
Lets discuss during the next weekly meeting. In case of Kazakhstan and Poland there is a need to have a name for the campaign in two or three languages.
