### ISSUE TITLE
Code verification backdrop doesnt show/hide the code

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#57]
**Describe the bug**
Code verification backdrop doesnd show/hide the code inputs correctly.

**To Reproduce**
1. Open [https://staging.usupport.online/client](https://staging.usupport.online/client) on mibile devide through the browser
2. Click on [https://staging.usupport.online/client/register](https://staging.usupport.online/client/register)
3. Enter your credentials
4. The backdrops slides from the bottom
5. Click on show/hide code

**Expected behavior**
The verification code to be correctly hidden/shown when the button is clicked.

**Screenshots**
![IMG_0569 (1)](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/a2d6fc92-e65d-49c2-8f3b-15ca1536c1b5)
![IMG_0568 (1)](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/31868706-3be3-4326-9ff9-22c5254754ff)

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone:**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 - Version [latest]

**Comment by sebastian-7DIGIT** [comment]
The implementation for this will come under Issue #56. Closing this issue, no further action is needed here.
