### ISSUE TITLE
Untranslated literals- Kazakh feedback

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#59]
**Describe the bug**
Reports of either inaccurate, or untranslated literals (e.g. article reading time)/content material e.g. My QA items; An additional Typo appears on the subject of the provider account registration notification email: “registraion” 

**Expected behavior**

**Screenshots**
<img width="604" alt="MicrosoftTeams-image (2)" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146742938/1af4ca5d-980f-4f2a-865f-cc9d385655a4">

**Additional context**

**Comment by sebastian-7DIGIT** [comment]
Ready for deployment.

**Comment by Gaskevych** [comment]
Dear @MiriamObibi  can you please verify and close if all works? Thanks!

**Comment by MiriamObibi** [comment]
Verified ok.
