### ISSUE TITLE
Provider calendar campaign unclickable- Kazakh feedback 

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#60]
**Describe the bug**
Calendar: Campaign was unclickable for some providers 

**To Reproduce**
Unable to reproduce (disabling JavaScript to see if this might have been the cause did not help, as the whole app doesn’t work without it). Needs to be checked by 7digit .

**Expected behavior**
Providers should be able to join a campaign by clicking on the three dots. 

**Additional context**

**Comment by sebastian-7DIGIT** [comment]
We tried to replicate the issue but we could not identify any. Following the right approach to interacting with the campaigns there was no issue for a provider to join an existing campaign.  Please provide more information about the encountered problem otherwise I would suggest closing this issue.

**Comment by mhdosman** [comment]
@MiriamObibi didn't find an issue here
