### ISSUE TITLE
Indistinguishable interfaces (Client and Provider web interfaces)

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#62]
**Describe the bug**
A provider seeking to access the provider’s interface from the link on the commercial website was unable to distinguish between the client and provider interfaces due to their similarities. 

**To Reproduce**
1. Go to the client interface (Web) and Provider interface
2. Observe the similarities

**Expected behavior**
Web app - As login screens are similar across the different interfaces, a distinguishing feature should be added

**Comment by gravitz** [comment]
Test comment

**Comment by sebastian-7DIGIT** [comment]
It appears to me that the problem isn't related to functionality but rather pertains to the need for adjustments in content or visuals.

@MiriamObibi we will require additional discussion for this.

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready to deploy

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT sorry, have you added to both client's and provider's interfaces or providers only? I checked the client one and don't see the updates.

**Comment by sebastian-7DIGIT** [comment]
The changes were implemented on all interfaces: client, provider, country-admin, and global-admin.

Client UI presents the distinguishable part on the following pages:
- Initial choose language & country page: https://staging.usupport.online/client/ 
- Login Page - https://staging.usupport.online/client/login

E.g.
![Screenshot 2023-11-02 at 12 38 58](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/95fb26be-dc75-4895-8540-359e0157dc4f)

Please let me know if you don't manage to see the adjustments.

**Comment by MiriamObibi** [comment]
Verified.
