### ISSUE TITLE
Remove duplicate settings at the very bottom of the site

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#63]
**Is your feature request related to a problem? Please describe.**
Remove duplicate settings at the very bottom of the site.

**Describe the solution you'd like**
Additional information is needed.

**Additional context**
Additional information is needed.

**Comment by sebastian-7DIGIT** [comment]
This issue was transferred from the UAT. We could not identify what it refers to. 

Please provide more information.

**Comment by Gaskevych** [comment]
@gravitz @MiriamObibi in case you know what this issue is about?

**Comment by gravitz** [comment]
@Gaskevych This appears to have originated from Kaibuldaev's report, where it had this screenshot

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/10649892/72ac1f77-d3c5-46b4-8a2e-9d470703d792)

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT please have a look at the screenshot - provided by Engelbert. Does it help?

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych I am not sure what is meant by this screenshot. Can you please point out the "duplicate settings" that need to be removed? From the screenshot, we can observe that there are 4 lines of different Kazakh words. That's as far as our understanding goes.
