### ISSUE TITLE
Login as a guesst loading issue

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#64]
**Describe the bug**
When logged in as a guest the app was loading indefinitely.

**To Reproduce**
1. Go to Usupport mobile
2. Login as a guest
3. Click on user profile

**Expected behavior**
Fast loading times

**Smartphone**
 - Device: [iphone]
 - OS: [latest]

**Comment by sebastian-7DIGIT** [comment]
Deployment complete, and changes available in the staging environment.

**Comment by Gaskevych** [comment]
@gravitz  can you please check and confirm? Thanks!

**Comment by gravitz** [comment]
@Gaskevych works as expected on Android. @MiriamObibi to verify on iOS which is where the issue was reported to have been observed.

**Comment by mhdosman** [comment]
confirm the same issue, 
https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/258c9855-e57d-4613-8854-18894db3013e

**Comment by sebastian-7DIGIT** [comment]
@mhdosman Due to changes required for the security testing of the mobile app, currently the server is being redeployed and the services won't work until the deployment is finalised.

**Comment by mhdosman** [comment]
well noted,

**Comment by mhdosman** [comment]
@Gaskevych I checked it again no problem, you can check and close it if it has been solved on your device,
