### ISSUE TITLE
Mobile Application UI Audit

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#65]
**Is the feature request related to a problem? Please describe.**

The mobile application's user interface has been subject to a recent design audit, which revealed various issues affecting the overall user experience. The issues are presented in the audit file.

**Describe the solution that is desired**

The desired solution involves implementing the suggested changes to the mobile application's user interface to address the issues identified during the audit.

**Additional context**

The design audit team has provided detailed feedback and recommendations, including screenshots.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych @MiriamObibi 

The changes for improving the Mobile app from a visual perspective, according to the conducted UI audit, were addressed and are now available to be checked.

The following file will present the changes that were implemented.

[App_Audit_Addresed.pdf](https://github.com/UNICEFECAR/USupport-entry-bundle/files/13295857/App_Audit_Addresed.pdf)

**Comment by MiriamObibi** [comment]
Verified ok.
