### ISSUE TITLE
Visual bug in "Register anonymously"

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#67]
**Describe the bug**
When typing password second icon of an eye appears

**To Reproduce**
1) Go to Register anonymously
2) Start typing password 
Note: Icon disappears when you start typing in other fields

**Expected behavior**
Showing only 1 icon

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge 
 - Version  117.0.2045.60
 
 
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/89eebb5b-83f3-4151-80f5-c31ab0795797)

**Comment by MiriamObibi** [comment]
Second icon of an eye not seen. @fomap please confirm and close

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych @MiriamObibi I think the issue was fixed could you please confirm? if everything is ok could you please close the current issue?
