### ISSUE TITLE
Misaligned language options

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#68]
**Describe the bug**
Misaligned language options in 
1) Login with email/Access token
2) Register with email
3) Register without email

**To Reproduce**
1. Go to https://staging.usupport.online/client/login OR  https://staging.usupport.online/client/register OR https://staging.usupport.online/client/register-anonymous
2. Click on language options

**Expected behavior**
Correctly aligned language options

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome / Edge / Yandex
 - Version   119.0.6045.106 / 119.0.2151.44 / 23.9.4.837

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/79923c0b-0835-4b37-af86-fb87946bfcef)

**Comment by sebastian-7DIGIT** [comment]
Deployment completed, and changes available in the staging environment.
