### ISSUE TITLE
Misalignment of text in "select provider"

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#69]
**Describe the bug**
Text is aligned to much to the left which reduced overall readability (RU/KK)

**To Reproduce**
1. Go to https://staging.usupport.online/client/select-provider 

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome / Edge / Yandex
Version 119.0.6045.106 / 119.0.2151.44 / 23.9.4.837

Chrome---
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/888c6126-6f3d-48a4-a23b-5f205aadcd54)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/19338c40-31ce-4e7a-985c-c62a1a8ff891)

Edge----
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/4f852eb7-4a18-49b7-ba20-90fe127e5d53)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/48100f3e-6285-4c17-a7e2-bbfba134a627)

Yandex---
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/577a5953-b7ba-448e-b9d2-e71515eadf9e)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/46d23a5d-ac79-44f9-ac50-791a1f0769bc)

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT Ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
Deployment complete, changes available in staging environment.

**Comment by mhdosman** [comment]
@MiriamObibi @Gaskevych I checked it using Chrome, Edge, Yandex, on 1920px and 1366px, didn't find an issue,

**Comment by mhdosman** [comment]
I think this can be closed
