### ISSUE TITLE
Duplication of messages in consultation chat

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#71]
**Describe the bug**
When leaving and returning back to consultation there is a duplication of previous messages if "show previous messages" is toggles

**To Reproduce**
1. Join consultation
2. Type message
3. Leave consultation and join again

Also can be achieved if you leave consultation, remove words after / and join

**Expected behavior**
No duplicates of the messages  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 118.0.5993.70
 
 
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/1a6a1cb0-6a86-40f9-a6f4-227bd6640a7e)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/6fdb0136-04c6-4751-8793-377e0c01c566)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/776ca82c-19c4-484f-b5e4-0238fbe500b3)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/683cf9b9-071c-48ba-b60b-30bc750c4c6d)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/f18c2f48-f8a2-436a-b291-056f0b77e9c8)

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT Changes implemented, and ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
The issue was fixed in the staging environment. The issue can be closed.
