### ISSUE TITLE
Service not working after rejoining consultation

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#72]
**Describe the bug**
Everything stops to work after rejoining consultation

**Smartphone (please complete the following information):**
 - Device: Samsung A12 
 - OS: Android 13.
 - Android app 

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/c4da2ab4-31cb-4f71-8f41-1aa9aa70959e)
![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/52755221/45d46ef6-0fa5-4c45-a49e-0402a4eb8677)

**Comment by Gaskevych** [comment]
@mhdosman  will add more details, we had this issue again during the testing

**Comment by mhdosman** [comment]
please see https://github.com/UNICEFECAR/USupport-entry-bundle/issues/105 for details

**Comment by Gaskevych** [comment]
We retested this issue and it was working fine.
