### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#73]
**Is your feature request related to a problem? Please describe.**
Database backup 

**Describe the solution you'd like**
The solution was agreed internally.

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT Dear Sebastian, should I just confirm that the database back up has been set up with the ps.kz? This is for tracking your activities, correct?

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych Yes that is correct, the database back up was implemented, tested and monitored and it is currently working as expected. You can confirm that this is in place.
