### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#74]
**Is your feature request related to a problem? Please describe.**
Implement the Dark mode for the client's mobile app and UI interface.

**Describe the solution you'd like**
Implement adjustments and necessary functionality for enabling dark mode for clients.

**Additional context**
Mobile interface has higher priority than web interface.

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment

**Comment by Gaskevych** [comment]
@MiriamObibi for your kind review.
