### ISSUE TITLE
Create Stripe accounts per country

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#75]
The system was meant to work with one centralized Stripe account. Since the Operating model has been revised, there is a need to set up different Stripe accounts for the countries, so the country-level partner will see and manage only the country-level payments.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych Please advice if we should still consider this as Priority 1? Also I think it will be a better approach to create Stripe accounts for each country when needed.

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT changed to Low priority as it is not planned to have Stripe accounts in the Kazakhstan pilot.

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych, I think this task can be closed following decision regarding to payments.
