### ISSUE TITLE
Unification of uSupport spelling

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#76]
Voting has been conducted on WhatsApp chat. Different documents and Deployment package have to be updated in line with the new spelling.

**Comment by sebastian-7DIGIT** [comment]
- [ ] Update static texts UIs
- [ ] Update static texts Mobile
- [ ] Update static error messages API
- [ ] Update logos

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment

**Comment by MiriamObibi** [comment]
Verified.
