### ISSUE TITLE
Allow clients to delete their chat history.

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#85]
**Describe the solution you'd like**
Add a new "Delete Chat" button next to the existing "Delete Account" button

**Additional context**
This functionality should be available on the Client Web and Mobile interfaces

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT Changes implemented and ready for deployment.

**Comment by sebastian-7DIGIT** [comment]
Changes were tested and are available in the staging environment for review.

**Comment by MiriamObibi** [comment]
Delete chat history button visible on mobile and Client web interfaces. Verified
