### ISSUE TITLE
Consultation- Issues with video and audio consultation both for provider and client (Edge, Chrome and Mobile)

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#86]
**Describe the bug**
On both the provider and client's interface, there were technical issues with hearing or seeing each other. Several attempts were made to log out and log back in. For the provider, switching browsers did not help, until both parties signed out completely and reconnected. On a different consultation, the client had to switch from IOS to Android, when there was no video or audio during the consultation. Android worked better. 

**To Reproduce**
Book a consultation and enter with the chat feature, then switch to video
Or enter with video feature. Both had the same output

**Expected behavior**
Every consultation should be void of audio visual issues. This feature should be tested extensively and should be reliable to deliver smoothly.

**Screenshots**
If applicable, add screenshots to help explain your [problem.](<img width="939" alt="Internet edge consultation issues" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146742938/7745afc5-98b5-4d28-a402-6c48bd574b21">)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych I think we can close this issue as there were many updates tot he related services since it was reported.

**Comment by Gaskevych** [comment]
Retested - everything was working fine.
