### ISSUE TITLE
Chat history adjustments

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#87]
**Is your feature request related to a problem? Please describe.**
Reviewed. There are some follow-up propositions on this.

**Describe the solution you'd like**
1. For the export, kindly remove the bubbles or make them smaller and concise. They appear too large and will require that too many pages are exported for a lengthy chat consultation.
2. The system messages are aligned, but the margins of the actual messages(chats) are too small on the sides (screenshot attached)

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/c219ffad-861a-46da-b892-5175892ce9c7)

3. Include time stamp to the export.

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment

**Comment by sebastian-7DIGIT** [comment]
Changes were deployed and tested. The issue is ready for review.

**Comment by Gaskevych** [comment]
@MiriamObibi please advise if it is fine to close this one?
