### ISSUE TITLE
On a small screen, content is not full-width

### ISSUE THREAD

**Issue by georgiganchev-7DIGIT** [UNICEFECAR/USupport-entry-bundle#89]
**Describe the bug**
On a small screen, content is not full-width

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gaskevych** [comment]
@MiriamObibi on my Iphone screen it looks fine, can you please also check this one and confirm? Thank you!

**Comment by MiriamObibi** [comment]
![IMG_4D840ED192BB-1](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146742938/01e5f8cf-31cf-4231-bd61-2a92f6cdda2a)
<img width="1512" alt="Screenshot 2024-01-25 at 03 16 58" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146742938/376ae720-3f63-4b8d-8c69-f88c7ac10f79">
@sebastian-7DIGIT  Are we also referring to the image or just the content? Image seems cut off in small screen on both iOS and android. The content appears ok on IOS and android.

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi, this issue refers only to content excluding the images coming from the CMS as the one presented in the screen captures above.

**Comment by mhdosman** [comment]
I think this can be closed
