### ISSUE TITLE
Client Profile Delete Functionality

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#90]
**Is your feature request related to a problem? Please describe.**
- No 

**Describe the solution you'd like**
- deleting a profile by a client should delete all their clinical and personal information like mood journal records and chat history. The physical client record itself should not be deleted.

**Additional context**
- Delete account functionality requires altering, to facilitate deletion of the above mentioned data points.

**Comment by sebastian-7DIGIT** [comment]
Changes were deployed and tested. The issue is ready for review.

**Comment by MiriamObibi** [comment]
Reviewed
