### ISSUE TITLE
Remove navbar Item

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#93]
Is your feature request related to a problem? Please describe.
The navigation bar on the Landing page has to many items.

Describe the solution you'd like
- [x] Remove "Contact us" item from the navigation menu 
- [x] Add a redirection link in the footer "Contact Us" so that users can click and be redirected to the Contact form page.

Additional context
None

**Comment by sebastian-7DIGIT** [comment]
@vasilen-7DIGIT ready for deployment

**Comment by sebastian-7DIGIT** [comment]
Changes were deployed and tested. The issue is ready for review.

**Comment by MiriamObibi** [comment]
Thanks @sebastian-7DIGIT reviewed. The link works well, but the 'Contact us' appears like a heading, since the phone number and address appears underneath it. The form may never be accessed. I suggest we move the phone number, add and email to the redirected link, under the form.

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi As agreed during the call. We will remove the contact information from the footer( email, address and phone) and we will keep the "Contact Us" heading.

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi changes were implemented and deployed. Ready for review.
