### ISSUE TITLE
Add new illustrations to website

### ISSUE THREAD

**Issue by sebastian-7DIGIT** [UNICEFECAR/USupport-entry-bundle#95]
**Is your feature request related to a problem? Please describe.**
New illustrations required for the Website Interface

**Describe the solution you'd like**
Add the new illustrations to the Website.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by Gaskevych** [comment]
can you please also add the square illustrations for sections from Figma? They are also final (screenshot below).

![block 3](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146723847/62e7cd72-0e54-43a7-8175-3b3821c1514f)

**Comment by sebastian-7DIGIT** [comment]
New illustrations in place, ready for deployment

MR: https://github.com/UNICEFECAR/USupport-website-ui/pull/38

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych please could we close this issue if there are no further comments?
