### ISSUE TITLE
uSupport Country Admin page is not showing any countries

### ISSUE THREAD

**Issue by mhdosman** [UNICEFECAR/USupport-entry-bundle#98]
**Describe the bug**
uSupport Country Admin page is not showing any countries

**To Reproduce**
1. Open https://usupport.online/country-admin/
2. Click on Country select,
3. It is empty

**Expected behavior**
To load countries and next languages after choosing a country.

**Screenshots**
<img width="960" alt="image" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/4c99868c-9190-47e9-8106-dea7bc5b1c62">

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser  Chrome Version 121.0.6167.140

**Comment by mhdosman** [comment]
I have assigned to this to [sebastian-7DIGIT](https://github.com/sebastian-7DIGIT), I am not sure whom to assign to,

**Comment by mhdosman** [comment]
I will close it now, waiting for an explanation from 7Digit

**Comment by sebastian-7DIGIT** [comment]
@mhdosman, please note that the link on which you were testing is the production environment which is not an active environment at this moment. 

Please use the staging environment which has all the functionalities up to date. Here is the link where you can test.

https://staging.usupport.online/country-admin/

**Comment by sebastian-7DIGIT** [comment]
@mhdosman can we close this issue? I think there should not be any adjustments needed at this moment in time.

**Comment by mhdosman** [comment]
it was misunderstood, closing it,
