### ISSUE TITLE
Articles Section Send your Suggestion is not working

### ISSUE THREAD

**Issue by mhdosman** [UNICEFECAR/USupport-entry-bundle#99]
**Describe the bug**
When clicking on send your suggestion, it is not sent, a red empty toast message is shown on the top of the screen for a few seconds and disappear

**To Reproduce**
1. Go to Articles section as a non-Registered user
2. Scroll down to the bottom,
3. fill the field of Give your suggestion,
4. click send
5. a red empty toast message appears on the top and noting being sent, 

**Expected behavior**
The suggestion to be sent and a success message to appear  or a message that you are not registered user, please register .

**Screenshots**

https://github.com/UNICEFECAR/USupport-entry-bundle/assets/153509442/008cf073-b0ab-47ee-99c3-cbaac880101e

**Smartphone (please complete the following information):**
 - Device: Samsung A54
 - OS: Android 12
 - Version : not stated in the app, where to look at the version?

**Comment by sebastian-7DIGIT** [comment]
@mhdosman issue identified, in the flow for not registered clients. 

Ready to address the issue.

**Comment by sebastian-7DIGIT** [comment]
Changes are ready for review.
